/*
 * Copyright (c) 1997, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Distribution License v. 1.0, which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

/* Generated By:JavaCC: Do not edit this line. SCDParserConstants.java */
package com.sun.xml.xsom.impl.scd;

/*-
 * #%L
 * XSOM
 * %%
 * Copyright (C) 2019 - 2020 Entur
 * %%
 * Licensed under the EUPL, Version 1.1 or – as soon they will be
 * approved by the European Commission - subsequent versions of the
 * EUPL (the "Licence");
 * 
 * You may not use this work except in compliance with the Licence.
 * You may obtain a copy of the Licence at:
 * 
 * http://ec.europa.eu/idabc/eupl5
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the Licence is distributed on an "AS IS" basis,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Licence for the specific language governing permissions and
 * limitations under the Licence.
 * #L%
 */

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public interface SCDParserConstants {

  int EOF = 0;
  int Letter = 6;
  int BaseChar = 7;
  int Ideographic = 8;
  int CombiningChar = 9;
  int UnicodeDigit = 10;
  int Extender = 11;
  int NCNAME = 12;
  int NUMBER = 13;
  int FACETNAME = 14;

  int DEFAULT = 0;

static final List<String> tokenImage = Collections.unmodifiableList(Arrays.asList(
        new String[] {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "<Letter>",
    "<BaseChar>",
    "<Ideographic>",
    "<CombiningChar>",
    "<UnicodeDigit>",
    "<Extender>",
    "<NCNAME>",
    "<NUMBER>",
    "<FACETNAME>",
    "\":\"",
    "\"/\"",
    "\"//\"",
    "\"attribute::\"",
    "\"@\"",
    "\"element::\"",
    "\"substitutionGroup::\"",
    "\"type::\"",
    "\"~\"",
    "\"baseType::\"",
    "\"primitiveType::\"",
    "\"itemType::\"",
    "\"memberType::\"",
    "\"scope::\"",
    "\"attributeGroup::\"",
    "\"group::\"",
    "\"identityContraint::\"",
    "\"key::\"",
    "\"notation::\"",
    "\"model::sequence\"",
    "\"model::choice\"",
    "\"model::all\"",
    "\"model::*\"",
    "\"any::*\"",
    "\"anyAttribute::*\"",
    "\"facet::*\"",
    "\"facet::\"",
    "\"component::*\"",
    "\"x-schema::\"",
    "\"x-schema::*\"",
    "\"*\"",
    "\"0\"",
  }));
}
