<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" version="1.0">

    <xsd:complexType name="MultilingualString" mixed="true">
        <xsd:sequence>
            <xsd:element name="Text" type="TextType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
        <xsd:attribute name="lang" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="Link" mixed="true">
        <xsd:attribute name="href" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="TextType">
        <xsd:simpleContent>
            <xsd:extension base="xsd:string">
                <xsd:attribute name="lang" type="xsd:string"/>
            </xsd:extension>
        </xsd:simpleContent>
    </xsd:complexType>
</xsd:schema>
