name: Validate, build and deploy to Maven Central
on:
  push:
    branches:
      - main

jobs:
  maven-build-and-releas:
    uses: entur/gha-maven-central/.github/workflows/maven-publish.yml@v1
    secrets: inherit
    with:
      next_version: minor
      version_strategy: tag
      version_tag_prefix: release-
